services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vendor\ExtensionSkeleton\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Middleware wird automatisch via RequestMiddlewares.php registriert
  Vendor\ExtensionSkeleton\Middleware\ExampleMiddleware:
    public: true
    tags:
      - name: 'event.listener'

  # Controller
  Vendor\ExtensionSkeleton\Controller\ExampleController:
    public: true
